# Generated by Django 4.2 on 2023-04-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
