# Generated by Django 4.2 on 2023-05-01 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=256)),
                ('answer', models.CharField(max_length=256)),
                ('is_correct', models.BooleanField(default=False)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.block')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=256)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.block')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=256, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('is_admin', models.BooleanField()),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=36)),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(max_length=256)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.block')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.lesson')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.questionanswer')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.user')),
            ],
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.test'),
        ),
        migrations.CreateModel(
            name='PassedLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.block')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.user')),
            ],
        ),
    ]
