# Generated by Django 4.2 on 2023-04-26 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_education_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.IntegerField()),
                ('content', models.TextField(blank=True)),
                ('block_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.block')),
            ],
        ),
        migrations.DeleteModel(
            name='Education',
        ),
    ]
