# Generated by Django 4.2 on 2023-05-13 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_questionanswer_test_user_testresult_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.block'),
        ),
        migrations.AlterField(
            model_name='test',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.lesson'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=0),
        ),
    ]
