# Generated by Django 4.2 on 2023-04-26 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_block_lesson_delete_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='block_id',
            new_name='block',
        ),
    ]
