# Generated by Django 4.2 on 2023-04-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_rename_block_id_lesson_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_name',
            field=models.CharField(),
        ),
    ]
